### ISSUE TITLE
VST Host 32/64 bit mixed plugin support

### ISSUE THREAD

**Issue by Drachenkaetzchen** [obiwanjacobi/vst.net#10]
Hi,

is there any documentation or any hints on how to load both 32 and 64 bit VST plugins from a VST.NET host implementation running 64 bit?

My idea was to compile both versions of VST.NET, but then I'd have duplicate namespaces for the assemblies. I might dig deeper into the issue at a later point in time, but any hints are appreciated.

Thanks
Felicia

**Comment by obiwanjacobi** [comment]
Never tried that. You would have to thunk the VST interface for methods that have different binary signatures in 32bit and 64bit.
https://github.com/obiwanjacobi/vst.net/blob/master/Source/Code/Jacobi.Vst.Interop/Host/VstPluginCommandStub.cpp

Then you'd have to detect if a plugin dll is 32bit or 64bit during loading and use the thunked or normal implementation of the command stub.
https://github.com/obiwanjacobi/vst.net/blob/master/Source/Code/Jacobi.Vst.Interop/Host/VstUnmanagedPluginContext.cpp

I guess it could be done.

**Comment by Drachenkaetzchen** [comment]
For reference: Here's how RtMidi.Core does it:

https://github.com/micdah/RtMidi.Core/tree/master/RtMidi.Core/Unmanaged/API

**Comment by obiwanjacobi** [comment]
After some research it seems that it is not possible to load a 32-bit dll (plugin) into a 64-bit host (exe).
Note that PInvoke (as the RtMidi example uses) will not work in our scenario,  because we have to load multiple plugin's dynamically. PInvoke statically names the dll to interop with.

64-bit hosts can only load 64-bit plugins and the same goes for 32-bit.
