### ISSUE TITLE
Can't create Cubase useable VST plugin with VST.NET in Visual Studio 2017

### ISSUE THREAD

**Issue by dansted** [obiwanjacobi/vst.net#16]
I would like to use VST.NET with visual studio 2017 to create vst's that I can use in Cubase.

I've tried to create a demo vst without any usefull content just to see if it could open up in Cubase, but Cubase couldn't even recognize the dll file as a vst plugin.

What I did:
- Created solution in Visual Studio 2017, added 3 projects to solution(Interop, Core, Framework).
- Added new project via AudioPluginTemplate to solution.
- Created _vst folder in Interop project, added aeffect.h and aeffectx.h files to it (download from another open source vst plugin, as I couldn't find them in Steinberg VST SDK).
- Deleted assembly.general and assembly.version from Interop, Core and Framework projects.
- Deleted all jacobi .snk key files from projects and unchecked sign assembly in all projects under properties.
- Right click solution -> retarget solution -> OK.
-Renamed Interop project to MyCustomVST, renamed AudioPluginTemplate project to MyCustomVST.net.
- Build Core and Framework project.
- Removed Interop, Core and Framework dependencies from all projects. Re-added dependencies with the newly build dlls.

These 4 projects build in visual studio without error, but I can't use the MyCustomVST.net.dll that was created, it doesn't get recognized as a vst dll with the hosts. I've tested with these vst hosts (vstHost, saviHost, Cubase).

Can you please help me, what am I doing wrong? Do you have a detailed guide to set up a project in visual studio 2017 from scratch for dummies like me?

**Comment by obiwanjacobi** [comment]
[Started at:
https://stackoverflow.com/questions/55768519/how-to-create-vst-plugins-with-c-sharp-vst-net-framework
After trying a couple of things we went back to a known working plugin: the Delay plugin sample]

So you've build the Delay sample. It is important to that all .dlls that were built stay together. If you look at the post build events of the Delay sample project, you'll see copy instructions to move and rename the necessary assemblies.

Also it would be interesting to know what actually goes wrong when trying to load the plugin in CuBase. If there are any messages you could share. Otherwise you could try to connect the Visual Studio Debugger by starting Cubase, selecting Attach... from the VS-Debug menu (with the delay sample project loaded) and then trying to open the plugin in CuBase.

(I have to get into it myself, for I have not touched this code in 5 years ;-)

**Comment by dansted** [comment]
Cubase doesn't crash or anything, it just doesn't display the plugin when searching the specific folder. 
It displays all other plugins. I copied all the build dlls to "C:\Users\mid\Downloads\VST_DLL_TESTS" and renamed Interop dll to "MyAudioVST.dll".
![1](https://user-images.githubusercontent.com/31686436/56759150-9c828480-6798-11e9-898b-3af187082226.png)

The "vsth-pw" plugin at the last line is the only plugin Cubase found in "C:\Users\mid\Downloads\VST_DLL_TESTS".
![2](https://user-images.githubusercontent.com/31686436/56759070-5decca00-6798-11e9-83c3-496d30c0c741.png)

**Comment by obiwanjacobi** [comment]
If you could set a breakpoint in your plugin root class' constructor - we at least will know if it is loading.
If it doesn't hit that breakpoint, you could try opening the interop project (C++) and set a breakpoint in VSTPluginMain (you will need to build a debug version of Jacobi.Vst.Interop)
https://github.com/obiwanjacobi/vst.net/blob/master/Source/Code/Jacobi.Vst.Interop/Jacobi.Vst.Interop.cpp

That is the entry point that should be called by the DAW/host.

You could also try to add a MyAudioVst.dll.config file and see if you can get it to trace any diagnostic messages. Use this as template: https://github.com/obiwanjacobi/vst.net/blob/master/Source/Code/Jacobi.Vst.Interop/app.config
and replace '[PluginName]' with 'MyAudioVST'...
You can even add/change event listeners to route these diagnostic messages - it uses the standard .NET TraceSource class.

I am totally in the dark on what might go wrong, so we're trying to see how far it gets...
If you can think of anything additional we could try, please share.

I seem to remember that CuBase specifically is very peculiar with VST plugins (which is odd because both are from Steinberg)...

**Comment by dansted** [comment]
I dont know if I've done it correctly, but I didn't hit any breakpoint.

I couldn't start in debug mode from Visual Studio because it is of type "class library". After I set a breakpoint in the constructor of my plugin I added a new
console application in order to be able to do so. I Attached Cubase to process in Visual Studio and changed Cubase VST look-up folder to my projects bin/debug, copied a Interop dll to the folder and renamed it and run debug. Then I updated VST's in Cubase but no breakpoint was hit.

**Comment by dansted** [comment]
I've re-installed my PC, upgraded from Visual Studio 2017 to 2019 and created a new test project.
Now if I build a x64 version of the plugin it will open in a x64 VSTHost. 

But if I install VST.NET x86 version from NuGet, change platform in configuration manager to x86 and build it. This version won't be listed in Cubase's VST plugin-list.

**Comment by dansted** [comment]
It worked!!
The only thing I needed to do after re-install was to install "vcredist_x86.exe".

Is it possible to somehow merge the dlls to a single useable vst dll. 
I've tried with costura and ILMerge. They merge alright but then the vst becomes unuseable.

**Comment by obiwanjacobi** [comment]
Argh, that damn C++ redistributable. I always forget about that - so sorry.

**Comment by dansted** [comment]
Thank you Obiwanjacobi for all your help :)

**Comment by obiwanjacobi** [comment]
No problem. 
Have fun with your project.
