### ISSUE TITLE
VST3

### ISSUE THREAD

**Issue by pzandvoort** [obiwanjacobi/vst.net#20]
Your comment in the VST3 section of the code says ** IT FAILED **. The interop looks solid... How did it fail?

**Comment by obiwanjacobi** [comment]
The VST3 interfaces are binary compatible with COM interfaces. The idea was to use .NET COM support to marshal calls to the .NET counterparts. I never got that working. I cannot remember the details but I think it had to do with the threading-mode (apartment-threading) of the main thread. I remember making several SO questions.
I also wanted it to be cross-platform and so I tried to use mono and experimented with using some internal API -can't remember the details- that also failed and back then the mono community was not very helpful.

**Comment by pzandvoort** [comment]
I had the same thought - it looks binary compatible with COM so .net should be able to do all the marshalling for me. I got to the point where the host would load the plugin, create the AudioProcessor but then crash on initializing the EditController, like it's missing a required interface or something. Did you get farther than that?

**Comment by obiwanjacobi** [comment]
I really don't remember, sorry. It was a long time ago and I have done many other things since.
But look at the SO questions I posted during that time - you may find something useful:

- COM interop: https://stackoverflow.com/questions/19465041/interop-com-isch-interface-marshaling-results-in-accessviotlationexception-on
- RCW exception: https://stackoverflow.com/questions/20371718/rcw-finalizer-access-violation
- COM interop 2: https://stackoverflow.com/questions/19479488/returned-managed-object-method-not-called-from-c-in-com-interop
- MTA threading: https://stackoverflow.com/questions/20824541/how-to-force-mta-on-all-threads-calling-from-3rd-party-unmanaged-process-into-ma

Hope it helps...

**Comment by pzandvoort** [comment]
No worries - thanks a lot.
