### ISSUE TITLE
Error when building Jacobi.Vst.Host.Interop

### ISSUE THREAD

**Issue by fgoulet** [obiwanjacobi/vst.net#33]
I'm not able to build the project Jacobi.Vst.Host.Interop

Error C1107 could not find assembly 'Microsoft.Extensions.Configuration.FileExtensions.dll': please specify the assembly search path using /AI or by setting the LIBPATH environment variable Jacobi.Vst.Host.Interop	C:\Users\frede\Source\Repos\vst.net\Source\Code\Jacobi.Vst.Interop\Bootstrapper.cpp	7

I have downloaded and added a reference to the missing assemby but I got the same error on building.

**Comment by fgoulet** [comment]
I manage to build it by adding both Microsoft.Extensions.Configuration.FileExtensions.dll and Microsoft.Extensions.Configuration.Json.dll to a local folder and the add them in referenced assemblies.

I'm not sure why I did not have to do that for Microsoft.Extensions.Configuration.dll and Microsoft.Extensions.Configuration.Abstractions.dll.

**Comment by obiwanjacobi** [comment]
Yeah - there is a problem with mixed C++/CLI projects in visual studio. I have an Issue open with the SDK-team on this - but that is progressing really slowly. This type of project does not work (well) with dotnet core nuget packages.

In order to build and run successfully you need all dependencies listed in the CLI (at the top of FindFiles.cs). These include dependencies of dependencies...

That being said, I do not recommend building the source code in general. At this stage though, while the last kinks are worked out of the system, it may be necessary.

**Comment by obiwanjacobi** [comment]
I just released RC2 - which might help you [2c]

**Comment by obiwanjacobi** [comment]
Closing - no other issues reported.
